source 'https://rubygems.org'

gem 'sinatra', '~> 2'
gem 'sinatra-contrib', '~> 2'
gem 'sinatra-cross_origin', '~> 0.4'
gem 'thin', '~> 1'
gem 'icalendar-recurrence', '~> 1'
gem 'tzinfo', '~> 1'
gem 'tzinfo-data'
gem 'activesupport', '~> 6.0'