source 'https://rubygems.org'

gem 'sinatra', '~> 2'
gem 'sinatra-contrib', '~> 2'
gem 'sinatra-cross_origin', '~> 0.4'
gem 'thin', '~> 1'
gem 'icalendar', '~> 2'
gem 'icalendar-recurrence', '~> 1'
gem 'tzinfo', '~> 2'
gem 'tzinfo-data', '>= 1.2020'
gem 'activesupport', '~> 3.2'